inherits = "tokyonight"
# Author: Paul Graydon <untimely.creation97@proton.me>

# rbns tweaks
"ui.cursor.primary.normal" = { bg = "white", fg="black"}
"ui.cursor.primary.insert" = { bg = "white", fg="black"}
"ui.cursor.primary.select" = { bg = "white", fg="black"}
"ui.linenr.selected" = { fg = "soft-red" }
"ui.statusline.normal" = { bg = "soft-red", fg = "bg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "light-green", fg = "bg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "light-blue", fg = "bg", modifiers = ["bold"] }
"ui.virtual.ruler" = {bg = "border"}

[palette]
soft-red = "#C55288"
red = "#f7768e"
white = "#ffffff"
black = "#000000"


# including the inherited palette as a comment to make working with this easier

# [palette]
# red = "#f7768e"
# orange = "#ff9e64"
# yellow = "#e0af68"
# light-green = "#9ece6a"
# green = "#73daca"
# aqua = "#2ac3de"
# teal = "#1abc9c"
# turquoise = "#89ddff"
# light-cyan = "#b4f9f8"
# cyan = "#7dcfff"
# blue = "#7aa2f7"
# purple = "#9d7cd8"
# magenta = "#bb9af7"
# comment = "#565f89"
# black = "#414868"

# add = "#449dab"
# change = "#6183bb"
# delete = "#914c54"

# error = "#db4b4b"
# info = "#0db9d7"
# hint = "#1abc9c"

# fg = "#c0caf5"
# fg-dark = "#a9b1d6"
# fg-gutter = "#3b4261"
# fg-linenr = "#737aa2"
# fg-selected = "#343a55"
# border = "#15161e"
# border-highlight = "#27a1b9"
# bg = "#1a1b26"
# bg-inlay = "#1a2b32"
# bg-selection = "#283457"
# bg-menu = "#16161e"
# bg-focus = "#292e42"
