# Author: Paul Graydon <untimely.creation97@proton.me>
inherits = "tokyonight"



# rbns tweaks
"ui.cursor.primary.normal" = { bg = "red" }  
"ui.cursor.primary.insert" = { bg = "red" }  
"ui.cursor.primary.select" = { bg = "red" }  
"ui.linenr.selected" = { fg = "red" }

[palette]
red = "#c7768e"
